### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by freidamachoi** [richardvanhook/databasedotcom-oauth2#1]
Trying to Query via OAuth2 (utilizing databasedotcom-oauth2) using Postgres as well (on Heroku) -- authentication no problem working very well; ability to query etc.. also working.

Trying to "Create/Save/Update" into Postgres is showing itself to be problematic.  I apologize up front for bugging you - but how would I do this with this gem?  I can via OmniAuth + OmniAuth-Salesforce, but the challenges on interaction with sf.com is a bit diffcult; dbdc-oauth2 gem overcomes that in a huge way, but now saving into Postgres is -- for my small brain at least -- proving impossible.  Any chance you have example?

**Comment by richardvanhook** [comment]
I'm a fan of the sequel gem.

**Comment by freidamachoi** [comment]
Thanks very much for response.  Sounds like a great idea.  btw - apex-lang is fantastic!
